spring.application.name=attendant

spring.datasource.url=jdbc:postgresql://localhost:5432/attendant
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.context-path=/api/v1